version: '3'

services:
  mysql:
    image: cryptnode-mysql:latest
    build:
      context: ./common/dev-mysql
    restart: unless-stopped
    networks:
      - cryptnode
    ports:
      - "127.0.0.1:13306:3306"
    volumes:
      - .:/node
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: cryptnode-redis:latest
    build:
      context: ./common/dev-redis
    restart: unless-stopped
    networks:
      - cryptnode
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - .:/cryptnode

networks:
  cryptnode:
    external:
      name: "cryptnode"

volumes:
  mysql_data:
